//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base.UI {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class FodyWeavers : global::System.Configuration.ApplicationSettingsBase {
        
        private static FodyWeavers defaultInstance = ((FodyWeavers)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new FodyWeavers())));
        
        public static FodyWeavers Default {
            get {
                return defaultInstance;
            }
        }
    }
}
